todo: main main_parallel main_parallel_parallel
main: main.cpp
	g++ -pthread -pg -o main main.cpp -Ilibarff libarff/arff_attr.cpp libarff/arff_data.cpp libarff/arff_instance.cpp libarff/arff_lexer.cpp libarff/arff_parser.cpp libarff/arff_scanner.cpp libarff/arff_token.cpp libarff/arff_utils.cpp libarff/arff_value.cpp
main_parallel: main_parallel.cpp
	g++-4.9 -pthread -o main_parallel main_parallel.cpp -Ilibarff libarff/arff_attr.cpp libarff/arff_data.cpp libarff/arff_instance.cpp libarff/arff_lexer.cpp libarff/arff_parser.cpp libarff/arff_scanner.cpp libarff/arff_token.cpp libarff/arff_utils.cpp libarff/arff_value.cpp
main_parallel_parallel: main_parallel_parallel.cpp
	g++ -pthread -std=gnu++11 -o main_parallel_parallel main_parallel_parallel.cpp -Ilibarff libarff/arff_attr.cpp libarff/arff_data.cpp libarff/arff_instance.cpp libarff/arff_lexer.cpp libarff/arff_parser.cpp libarff/arff_scanner.cpp libarff/arff_token.cpp libarff/arff_utils.cpp libarff/arff_value.cpp
clean:
	rm main main_parallel main_parallel_parallel
