todo: hello hello2 hello3 nonblocking scatter gather gather2
hello: hello.c
	mpicc hello.c -o hello
hello2: hello2.c
	mpicc hello2.c -o hello2
hello3: hello3.c
	mpicc hello3.c -o hello3
nonblocking: nonblocking.c
	mpicc nonblocking.c -o nonblocking	
scatter: scatter.c
	mpicc scatter.c -o scatter		
gather: gather.c
	mpicc gather.c -o gather			
gather2: gather2.c
	mpicc gather2.c -o gather2
clean:
	rm hello hello2 hello3 nonblocking scatter gather gather2
